### PR TITLE
feat(upgrade): add support to navigation v6

### PR DESCRIPTION
**Pull request by torgeadelin**
# Description

This is some initial work to make the library compatible with react-navigation v6.
I have tested this and seems to be working fine with v6. The current release also seems to work, these changes only make some prop nam changes.

# Important
Before testing these changes, or even the current release with v6 please make sure you install v6 properly first, and then try to use this library. Here's some docs to help with that:
- https://reactnavigation.org/docs/getting-started
- https://reactnavigation.org/docs/upgrading-from-5.x

### CODE REVIEW

**Comment by afkcodes** [comment]
will use the v6 branch and test it out, thanks @torgeadelin

**Comment by afkcodes** [comment]
Hey @torgeadelin i tried this with react navigation6 the `navigation-v6-support` branch but it was giving me error.

**Comment by torgeadelin** [comment]
@afkcodes make sure to install the react navigation requirements correctly before, remove all node_modules, clear cache, and then install this branch's version. I recommend doing it via `npm pack` which will generate a zip folder that can then be installed with `npm  install path/to/file.zip`. Hope this helps!

**Comment by reyakov** [comment]
Everything look good, when will you merge it?

**Comment by Sudhir9026** [comment]
I am unable to save master branch when you are going to provide support to v6?

**Comment by c-fitzmaurice** [comment]
Other than GitHub actions closing this, any reason why v6 support was not released? Would love to use this in an Expo application.

**Comment by torgeadelin** [comment]
As I've mentioned above, the existing version seems to be compatible with v6 already. The changes in this PR fixes some minor bugs.

**Comment by torgeadelin** [comment]
I'll try to merge this soon. It would be great if more people can test everything works with v6 tho.

**Pull request closed without merging**
