### PR TITLE
fix: bug when pressing hardware button to go back on android

### PR DESCRIPTION
**Pull request by mayconpaivac**

### CODE REVIEW

**Comment by torgeadelin** [comment]
Not sure.. how does this solve the problem?
I thought the hardware button go back has been fixed already

**Comment by mayconpaivac** [comment]
When using the latest version of this package, the back button on android does not work.

Changing the return true to false in the handleBackPress method solves the problem.

https://reactnative.dev/docs/backhandler#pattern

**Comment by papidb** [comment]
Hey, please what is the update with this?

**Comment by torgeadelin** [comment]
I'll push an update tonight.

**Comment by torgeadelin** [comment]
Issue should be fixed, please update to 3.1.4.
Also, thanks a lot for the contribution @mayconpaivac !

**Pull request merged**
