### PR TITLE
Fix for react navigation 5

### PR DESCRIPTION
**Pull request by fr3fou**
#15

### CODE REVIEW

**Comment by fr3fou** [comment]
this is almost fixed, works the exact same with with some changes to the API to match the one from react navigation 5:
```js
tapBarIcon: ({ color, focused }) =>
// instead of
tapBarIcon: ({ tintColor, focused }) =>
```
I've updated the README for those changes.

**Comment by fr3fou** [comment]
So I finished refactoring it, it's now a functional component instead of a class component and it uses hooks.

**Comment by fr3fou** [comment]
The updated example is now on the latest react native version.

**Comment by lyubchev** [comment]
When will this be merged?

**Comment by torgeadelin** [comment]
Hey! I’ll have a loot over the weekend.

**Comment by torgeadelin** [comment]
Hi, @fr3fou sorry for the slight delay.

I noticed you've pushed a lot of unnecessary files like pods. If you look at the additions there's more than 2.5 million additions and a lot of removals. 

Please make sure you only change what is required and also only push those changes.

**Comment by torgeadelin** [comment]
Hi, @fr3fou sorry for the slight delay.

I noticed you've pushed a lot of unnecessary files like pods. If you look at the additions there's more than 2.5 million additions and a lot of removals. 

Please make sure you only change what is required and also only push those changes.

**Comment by fr3fou** [comment]
I removed the pods in my branch, but for some reason that commit isn't appearing here?

**Comment by torgeadelin** [comment]
Yes, I think you have to make a new one. Also make sure the examples run.

**Comment by fr3fou** [comment]
i made a new one - #16

**Pull request closed without merging**
